services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/tama-kiisu.db
    volumes:
      - ./data:/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "cmd/migrate/main.go"]
    environment:
      - DB_PATH=/data/tama-kiisu.db
    volumes:
      - ./data:/data